package com.gojek.model;

/**
 * Created by Gaurav on 04/04/18.
 */
public enum Command {


    CREATE_PARKING_LOT, PARK, LEAVE, STATUS, REGISTRATION_NUMBERS_FOR_CARS_WITH_COLOUR, SLOT_NUMBERS_FOR_CARS_WITH_COLOUR, SLOT_NUMBER_FOR_REGISTRATION_NUMBER;


}
